import type { TechnologyAdapterDescriptor } from "./adapterSdk.js";
import { adapter } from "./externalTechnologyAdapterHelpers.js";

export const DEPLOYMENT_TARGETS: TechnologyAdapterDescriptor[] = [
  adapter({
    id: "apple-app-store",
    label: "Apple App Store",
    category: "deployment_target",
    supportedVersions: ["App Store Connect API v1"],
    latestCompatibleStableVersion: "App Store Connect API v1",
    supportedPlatforms: ["ios", "macos"],
    supportedArchitectures: ["arm64"],
    installation: {
      method: "App Store Connect API key",
      requiresProvisioning: true,
      requiredToolchain: ["xcrun altool / notarytool"],
    },
    authentication: {
      required: true,
      kind: "service_account",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: [],
      build: null,
      test: null,
      runtime: null,
      packaging: null,
      deploy: "xcrun altool --upload-app",
      healthCheck: null,
    },
    capabilityTests: ["app_store_connect_auth_check"],
    securityChecks: ["code_signing_verification", "notarization_check"],
  }),
  adapter({
    id: "google-play",
    label: "Google Play Console",
    category: "deployment_target",
    supportedVersions: ["Android Publisher API v3"],
    latestCompatibleStableVersion: "Android Publisher API v3",
    supportedPlatforms: ["android"],
    supportedArchitectures: ["arm64"],
    installation: {
      method: "Google Play service account",
      requiresProvisioning: true,
      requiredToolchain: ["Play Developer API client"],
    },
    authentication: {
      required: true,
      kind: "service_account",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: [],
      build: null,
      test: null,
      runtime: null,
      packaging: null,
      deploy: "Play Developer API edits.tracks.update",
      healthCheck: null,
    },
    capabilityTests: ["play_console_auth_check"],
    securityChecks: ["signing_verification"],
  }),
  adapter({
    id: "chrome-web-store",
    label: "Chrome Web Store",
    category: "deployment_target",
    supportedVersions: ["Chrome Web Store API v1.1"],
    latestCompatibleStableVersion: "Chrome Web Store API v1.1",
    supportedPlatforms: ["linux"],
    supportedArchitectures: ["x86_64"],
    installation: {
      method: "Chrome Web Store publish API credentials",
      requiresProvisioning: true,
      requiredToolchain: ["chrome-webstore-upload CLI"],
    },
    authentication: {
      required: true,
      kind: "oauth",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: [],
      build: null,
      test: null,
      runtime: null,
      packaging: null,
      deploy: "chrome-webstore-upload upload --auto-publish",
      healthCheck: null,
    },
    capabilityTests: ["webstore_auth_check", "manifest_v3_validation"],
    securityChecks: ["permission_review"],
  }),
];
