import type { TechnologyAdapterDescriptor } from "./adapterSdk.js";
import { adapter } from "./externalTechnologyAdapterHelpers.js";

export const GAME_ENGINES: TechnologyAdapterDescriptor[] = [
  adapter({
    id: "unreal-engine",
    label: "Unreal Engine",
    category: "game_engine",
    supportedVersions: ["5.3", "5.4", "5.5"],
    latestCompatibleStableVersion: "5.5",
    supportedPlatforms: ["windows", "macos", "linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "Epic Games Launcher / Unreal Engine source build",
      requiresProvisioning: true,
      requiredToolchain: ["Visual Studio or Xcode", "Unreal Build Tool"],
    },
    authentication: {
      required: true,
      kind: "oauth",
      credentialIsolation: "disposable_runner",
    },
    commands: {
      install: ["./Setup.sh", "./GenerateProjectFiles.sh"],
      build: "UnrealBuildTool Development",
      test: "RunUAT.sh BuildCookRun -run",
      runtime: null,
      packaging: "RunUAT.sh BuildCookRun -package",
      deploy: null,
      healthCheck: null,
    },
    capabilityTests: ["compile_empty_project", "cook_content", "package_build"],
    securityChecks: ["dependency_scan", "signing_verification"],
  }),
  adapter({
    id: "unity-engine",
    label: "Unity",
    category: "game_engine",
    supportedVersions: ["2022 LTS", "6000 LTS"],
    latestCompatibleStableVersion: "6000 LTS",
    supportedPlatforms: ["windows", "macos", "linux", "android", "ios", "web"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "Unity Hub managed editor install",
      requiresProvisioning: true,
      requiredToolchain: ["Unity Hub", "platform build support modules"],
    },
    authentication: {
      required: true,
      kind: "license_key",
      credentialIsolation: "disposable_runner",
    },
    commands: {
      install: ["unityhub --headless install --version <version>"],
      build: "Unity -batchmode -quit -executeMethod Builder.Build",
      test: "Unity -runTests -testPlatform PlayMode",
      runtime: null,
      packaging: "Unity -batchmode -buildTarget",
      deploy: null,
      healthCheck: null,
    },
    capabilityTests: [
      "compile_empty_project",
      "run_playmode_tests",
      "build_target",
    ],
    securityChecks: ["dependency_scan", "signing_verification"],
  }),
  adapter({
    id: "godot-engine",
    label: "Godot",
    category: "game_engine",
    supportedVersions: ["4.2", "4.3", "4.4"],
    latestCompatibleStableVersion: "4.4",
    supportedPlatforms: ["windows", "macos", "linux", "android", "ios", "web"],
    supportedArchitectures: ["x86_64", "arm64", "wasm"],
    installation: {
      method: "Godot headless editor binary download",
      requiresProvisioning: true,
      requiredToolchain: ["godot headless binary", "export templates"],
    },
    authentication: {
      required: false,
      kind: "none",
      credentialIsolation: "not_applicable",
    },
    commands: {
      install: ["curl -L godot headless binary", "download export templates"],
      build: "godot --headless --export-release",
      test: "godot --headless --script res://tests/run_tests.gd",
      runtime: "godot --headless",
      packaging: "godot --headless --export-release",
      deploy: null,
      healthCheck: null,
    },
    capabilityTests: [
      "compile_empty_project",
      "run_headless_tests",
      "export_release",
    ],
    securityChecks: ["dependency_scan"],
  }),
];
