import type { TechnologyAdapterDescriptor } from "./adapterSdk.js";
import { adapter } from "./externalTechnologyAdapterHelpers.js";

export const MOBILE_DESKTOP_TOOLCHAINS: TechnologyAdapterDescriptor[] = [
  adapter({
    id: "flutter-sdk",
    label: "Flutter SDK",
    category: "mobile_toolchain",
    supportedVersions: ["3.24", "3.27"],
    latestCompatibleStableVersion: "3.27",
    supportedPlatforms: ["android", "ios", "web", "windows", "macos", "linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "flutter channel stable + flutter precache",
      requiresProvisioning: true,
      requiredToolchain: [
        "Dart SDK",
        "Android SDK or Xcode for device targets",
      ],
    },
    authentication: {
      required: false,
      kind: "none",
      credentialIsolation: "not_applicable",
    },
    commands: {
      install: ["flutter channel stable", "flutter precache"],
      build: "flutter build apk | flutter build ios",
      test: "flutter test",
      runtime: "flutter run",
      packaging: "flutter build appbundle",
      deploy: null,
      healthCheck: "flutter doctor",
    },
    capabilityTests: ["flutter_doctor", "flutter_test", "flutter_build_apk"],
    securityChecks: ["dependency_scan", "pub_audit"],
    // The existing flutter-firebase stack adapter already generates real
    // Dart source, but the Flutter SDK itself has not been provisioned or
    // built in a verified runner yet, so this stays at "discovered".
  }),
  adapter({
    id: "xcode-apple-toolchain",
    label: "Xcode / Apple Developer Toolchain",
    category: "mobile_toolchain",
    supportedVersions: ["15", "16"],
    latestCompatibleStableVersion: "16",
    supportedPlatforms: ["macos", "ios"],
    supportedArchitectures: ["arm64", "x86_64"],
    installation: {
      method: "Xcode.app via Apple Developer / App Store, macOS-only runner",
      requiresProvisioning: true,
      requiredToolchain: ["Xcode command line tools", "provisioning profiles"],
    },
    authentication: {
      required: true,
      kind: "service_account",
      credentialIsolation: "disposable_runner",
    },
    commands: {
      install: ["xcode-select --install"],
      build: "xcodebuild -scheme <scheme> build",
      test: "xcodebuild test -destination 'platform=iOS Simulator'",
      runtime: "xcrun simctl boot <device>",
      packaging: "xcodebuild -exportArchive",
      deploy: "xcrun altool --upload-app",
      healthCheck: "xcodebuild -version",
    },
    capabilityTests: ["xcodebuild_version", "simulator_boot", "archive_export"],
    securityChecks: ["code_signing_verification", "provisioning_profile_check"],
  }),
  adapter({
    id: "android-sdk-gradle",
    label: "Android SDK + Gradle",
    category: "mobile_toolchain",
    supportedVersions: ["API 34", "API 35"],
    latestCompatibleStableVersion: "API 35",
    supportedPlatforms: ["android", "linux", "macos", "windows"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "sdkmanager managed Android SDK + Gradle wrapper",
      requiresProvisioning: true,
      requiredToolchain: [
        "Java 17+",
        "Android command line tools",
        "Gradle wrapper",
      ],
    },
    authentication: {
      required: false,
      kind: "service_account",
      credentialIsolation: "disposable_runner",
    },
    commands: {
      install: ["sdkmanager --install 'platforms;android-35'"],
      build: "./gradlew assembleRelease",
      test: "./gradlew test connectedAndroidTest",
      runtime: "emulator -avd <device>",
      packaging: "./gradlew bundleRelease",
      deploy: null,
      healthCheck: "sdkmanager --list_installed",
    },
    capabilityTests: ["gradle_build", "emulator_boot", "bundle_release"],
    securityChecks: ["dependency_scan", "signing_verification"],
  }),
  adapter({
    id: "electron-desktop",
    label: "Electron",
    category: "desktop_toolchain",
    supportedVersions: ["30", "31", "32"],
    latestCompatibleStableVersion: "32",
    supportedPlatforms: ["windows", "macos", "linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "npm install electron electron-builder",
      requiresProvisioning: false,
      requiredToolchain: ["Node.js", "electron-builder"],
    },
    authentication: {
      required: false,
      kind: "none",
      credentialIsolation: "not_applicable",
    },
    commands: {
      install: ["npm ci"],
      build: "npm run build",
      test: "npm test",
      runtime: "npm run start",
      packaging: "npm run electron:package",
      deploy: null,
      healthCheck: null,
    },
    capabilityTests: ["npm_build", "electron_launch", "installer_package"],
    securityChecks: ["dependency_scan", "electron_security_checklist"],
    // The electron-react stack adapter already generates real scaffold code,
    // but Electron itself has not been installed/built in a verified runner.
  }),
  adapter({
    id: "tauri-toolchain",
    label: "Tauri",
    category: "desktop_toolchain",
    supportedVersions: ["2.0", "2.1"],
    latestCompatibleStableVersion: "2.1",
    supportedPlatforms: ["windows", "macos", "linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "cargo install tauri-cli",
      requiresProvisioning: true,
      requiredToolchain: ["Rust toolchain", "platform WebView runtime"],
    },
    authentication: {
      required: false,
      kind: "none",
      credentialIsolation: "not_applicable",
    },
    commands: {
      install: ["rustup default stable"],
      build: "npm run tauri build",
      test: "cargo test",
      runtime: "npm run tauri dev",
      packaging: "npm run tauri build",
      deploy: null,
      healthCheck: null,
    },
    capabilityTests: ["cargo_build", "tauri_dev_launch", "installer_package"],
    securityChecks: ["dependency_scan", "cargo_audit"],
  }),
];
