import type { TechnologyAdapterDescriptor } from "./adapterSdk.js";
import { adapter } from "./externalTechnologyAdapterHelpers.js";

export const CLOUD_PLATFORMS: TechnologyAdapterDescriptor[] = [
  adapter({
    id: "fly-io",
    label: "Fly.io",
    category: "cloud_platform",
    supportedVersions: ["v2 machines API"],
    latestCompatibleStableVersion: "v2 machines API",
    supportedPlatforms: ["linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "flyctl CLI",
      requiresProvisioning: false,
      requiredToolchain: ["flyctl"],
    },
    authentication: {
      required: true,
      kind: "api_key",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: ["curl -L https://fly.io/install.sh | sh"],
      build: "flyctl deploy --build-only",
      test: null,
      runtime: null,
      packaging: null,
      deploy: "flyctl deploy",
      healthCheck: "flyctl status",
    },
    capabilityTests: ["flyctl_auth_check", "deploy_dry_run"],
    securityChecks: ["secrets_scoped_per_app"],
    // AppForge already deploys real projects to Fly.io.
    state: "deployable",
    evidence: {
      discovered: true,
      installVerified: true,
      compileOrBuildVerified: true,
      runtimeVerified: true,
      packageVerified: true,
      deploymentVerified: true,
    },
  }),
  adapter({
    id: "vercel",
    label: "Vercel",
    category: "cloud_platform",
    supportedVersions: ["v2 deployments API"],
    latestCompatibleStableVersion: "v2 deployments API",
    supportedPlatforms: ["linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "Vercel CLI / REST API",
      requiresProvisioning: false,
      requiredToolchain: ["vercel CLI"],
    },
    authentication: {
      required: true,
      kind: "api_key",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: ["npm install -g vercel"],
      build: "vercel build",
      test: null,
      runtime: null,
      packaging: null,
      deploy: "vercel deploy --prebuilt",
      healthCheck: "vercel inspect",
    },
    capabilityTests: ["vercel_auth_check", "deploy_dry_run"],
    securityChecks: ["secrets_scoped_per_project"],
  }),
  adapter({
    id: "aws",
    label: "Amazon Web Services",
    category: "cloud_platform",
    supportedVersions: ["current"],
    latestCompatibleStableVersion: "current",
    supportedPlatforms: ["linux"],
    supportedArchitectures: ["x86_64", "arm64"],
    installation: {
      method: "AWS CLI v2 / SDK",
      requiresProvisioning: true,
      requiredToolchain: ["aws CLI", "IAM role"],
    },
    authentication: {
      required: true,
      kind: "service_account",
      credentialIsolation: "scoped_secret",
    },
    commands: {
      install: ["install aws CLI v2"],
      build: null,
      test: null,
      runtime: null,
      packaging: null,
      deploy: "aws cloudformation deploy",
      healthCheck: "aws sts get-caller-identity",
    },
    capabilityTests: ["sts_identity_check"],
    securityChecks: ["least_privilege_iam", "secrets_manager_only"],
  }),
];
