/**
 * Baseline runnable scaffolds for every AppForge tech stack.
 */
type Files = Record<string, string>;

export function getStackScaffold(techStack: string): Files {
  return {
    "package.json": JSON.stringify({ name: techStack, private: true, version: "0.1.0" }, null, 2),
    "README.md": `# ${techStack}\n\nGenerated by AppForge.\n`,
  };
}

export function mergeScaffoldWithGenerated(
  scaffold: Files,
  generated: Files,
): Files {
  const out: Files = { ...scaffold, ...generated };
  if (scaffold["package.json"] && generated["package.json"]) {
    try {
      const base = JSON.parse(scaffold["package.json"]) as Record<string, any>;
      const over = JSON.parse(generated["package.json"]) as Record<string, any>;
      out["package.json"] = JSON.stringify(
        {
          ...base,
          ...over,
          scripts: { ...(base.scripts || {}), ...(over.scripts || {}) },
          dependencies: { ...(base.dependencies || {}), ...(over.dependencies || {}) },
          devDependencies: {
            ...(base.devDependencies || {}),
            ...(over.devDependencies || {}),
          },
        },
        null,
        2,
      );
    } catch {
      // keep generated
    }
  }
  return out;
}

export default { getStackScaffold, mergeScaffoldWithGenerated };
