/**
 * Baseline runnable scaffolds for every AppForge tech stack.
 * Generated LLM files are merged on top (generated wins on path conflict;
 * package.json dependencies are deep-merged).
 */

type Files = Record<string, string>;

function pkg(name: string, extra: Record<string, unknown> = {}): string {
  const { scripts, dependencies, devDependencies, ...rest } = extra;
  return JSON.stringify(
    {
      name,
      private: true,
      version: "0.1.0",
      type: "module",
      ...rest,
      scripts: {
        dev: "vite",
        build: "tsc -b && vite build",
        start: "vite preview",
        test: "vitest run",
        ...(scripts as object | undefined),
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        ...(dependencies as object | undefined),
      },
      devDependencies: {
        "@types/react": "^18.2.55",
        "@types/react-dom": "^18.2.19",
        "@vitejs/plugin-react": "^4.2.1",
        typescript: "^5.3.3",
        vite: "^5.1.0",
        vitest: "^1.2.2",
        ...(devDependencies as object | undefined),
      },
    },
    null,
    2,
  );
}

const GITIGNORE = `node_modules\ndist\n.env\n.env.local\ncoverage\n.DS_Store\n`;

function viteReactShell(
  title: string,
  extraDeps: Record<string, string> = {},
): Files {
  return {
    "package.json": pkg(title.toLowerCase().replace(/\s+/g, "-"), {
      dependencies: extraDeps,
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        test: "vitest run",
      },
    }),
    "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
export default defineConfig({ plugins: [react()], server: { port: 5173 } });
`,
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "ESNext",
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          jsx: "react-jsx",
          moduleResolution: "bundler",
          strict: true,
          skipLibCheck: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "src/main.tsx": `import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App";
createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
    "src/App.tsx": `export function App() {
  return (
    <main style={{ fontFamily: "system-ui", padding: 24 }}>
      <h1>${title}</h1>
      <p>Generated by AppForge. Replace this shell with your product UI.</p>
    </main>
  );
}
`,
    "README.md": `# ${title}\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    ".gitignore": GITIGNORE,
  };
}

function expressApiShell(title: string): Files {
  return {
    "package.json": pkg(title.toLowerCase().replace(/\s+/g, "-"), {
      scripts: {
        dev: "tsx watch src/server.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/server.js",
        test: "vitest run",
      },
      dependencies: {
        express: "^4.18.2",
        cors: "^2.8.5",
        helmet: "^7.1.0",
        zod: "^3.22.4",
      },
      devDependencies: {
        "@types/express": "^4.17.21",
        "@types/cors": "^2.8.17",
        "@types/node": "^20.11.16",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
        vitest: "^1.2.2",
      },
    }),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "src/server.ts": `import express from "express";
import cors from "cors";
import helmet from "helmet";

const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json());

app.get("/health", (_req, res) => res.json({ ok: true }));
app.get("/api/hello", (_req, res) => res.json({ message: "Hello from ${title}" }));

const port = Number(process.env.PORT || 3000);
app.listen(port, () => console.log("listening on " + port));
`,
    "README.md": `# ${title}\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    ".gitignore": GITIGNORE,
  };
}

function pythonAgentShell(title: string): Files {
  return {
    "requirements.txt":
      "openai>=1.30.0\npython-dotenv>=1.0.0\nhttpx>=0.27.0\npydantic>=2.0.0\n",
    "pyproject.toml": `[project]\nname = "${title.toLowerCase().replace(/\s+/g, "-")}"\nversion = "0.1.0"\nrequires-python = ">=3.10"\ndependencies = ["openai", "python-dotenv", "httpx", "pydantic"]\n`,
    "main.py": `"""${title} — AppForge agent scaffold."""
from __future__ import annotations
import os
from dotenv import load_dotenv

load_dotenv()

def run(prompt: str) -> str:
    """Replace with your tool-calling agent loop."""
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("BUILT_IN_FORGE_API_KEY")
    if not api_key:
        return "Set OPENAI_API_KEY to run this agent. Prompt was: " + prompt
    return f"[{title}] received: {prompt}"

if __name__ == "__main__":
    print(run("hello"))
`,
    "README.md": `# ${title}\n\n\`\`\`bash\npython -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt\npython main.py\n\`\`\`\n`,
    ".gitignore": `.venv\n__pycache__\n.env\n`,
  };
}

const SCAFFOLDS: Record<string, () => Files> = {
  "react-node": () => ({
    ...viteReactShell("React Node App", { express: "^4.18.2" }),
    "server/index.ts": `import express from "express";
const app = express();
app.get("/health", (_req, res) => res.json({ ok: true }));
app.listen(3000, () => console.log("API on :3000"));
`,
  }),
  "next-node": () => ({
    "package.json": pkg("next-app", {
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        test: "vitest run",
      },
      dependencies: {
        next: "^14.1.0",
        react: "^18.2.0",
        "react-dom": "^18.2.0",
      },
    }),
    "app/page.tsx": `export default function Page() {
  return <main><h1>Next.js AppForge app</h1></main>;
}
`,
    "app/layout.tsx": `export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>;
}
`,
    "next.config.mjs":
      "/** @type {import('next').NextConfig} */\n const nextConfig = {};\nexport default nextConfig;\n".replace(
        " const",
        "const",
      ),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          jsx: "preserve",
          strict: true,
          moduleResolution: "bundler",
          module: "esnext",
          target: "ES2020",
        },
        include: ["app", "src"],
      },
      null,
      2,
    ),
    "README.md": "# Next.js App\n\n```bash\nnpm install\nnpm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "vue-node": () => ({
    "package.json": pkg("vue-app", {
      dependencies: { vue: "^3.4.0" },
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
    }),
    "index.html": `<!doctype html><html><head><meta charset="UTF-8"/><title>Vue App</title></head><body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>`,
    "src/main.ts": `import { createApp } from "vue";\nimport App from "./App.vue";\ncreateApp(App).mount("#app");\n`,
    "src/App.vue": `<template><main><h1>Vue AppForge app</h1></main></template>\n`,
    "vite.config.ts": `import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\nexport default defineConfig({ plugins: [vue()] });\n`,
    "README.md": "# Vue App\n\n```bash\nnpm i && npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "svelte-node": () => ({
    "package.json": pkg("svelte-app", {
      dependencies: { svelte: "^4.2.0" },
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      devDependencies: {
        "@sveltejs/vite-plugin-svelte": "^3.0.0",
        vite: "^5.1.0",
        typescript: "^5.3.3",
      },
    }),
    "index.html": `<!doctype html><html><head><meta charset="UTF-8"/><title>Svelte App</title></head><body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>`,
    "src/main.ts": `import App from "./App.svelte";\nnew App({ target: document.getElementById("app")! });\n`,
    "src/App.svelte": `<script>const title = "Svelte AppForge app";</script>\n<main><h1>{title}</h1></main>\n`,
    "vite.config.ts": `import { defineConfig } from "vite";\nimport { svelte } from "@sveltejs/vite-plugin-svelte";\nexport default defineConfig({ plugins: [svelte()] });\n`,
    "README.md": "# Svelte App\n\n```bash\nnpm i && npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "angular-node": () => ({
    "package.json": pkg("angular-app", {
      scripts: {
        start: "ng serve",
        build: "ng build",
        test: "ng test",
      },
      dependencies: {
        "@angular/core": "^17.0.0",
        "@angular/platform-browser": "^17.0.0",
        "@angular/common": "^17.0.0",
        "@angular/compiler": "^17.0.0",
        rxjs: "^7.8.0",
        tslib: "^2.6.0",
        "zone.js": "^0.14.0",
      },
      devDependencies: {
        "@angular/cli": "^17.0.0",
        typescript: "^5.3.3",
      },
    }),
    "src/main.ts": `import { bootstrapApplication } from "@angular/platform-browser";\nimport { Component } from "@angular/core";\n@Component({ standalone: true, selector: "app-root", template: "<h1>Angular AppForge app</h1>" })\nclass App {}\nbootstrapApplication(App);\n`,
    "README.md": "# Angular App\n\n```bash\nnpm i && npm start\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "remix-node": () => ({
    "package.json": pkg("remix-app", {
      scripts: {
        dev: "remix vite:dev",
        build: "remix vite:build",
        start: "remix-serve ./build/server/index.js",
      },
      dependencies: {
        "@remix-run/node": "^2.5.0",
        "@remix-run/react": "^2.5.0",
        "@remix-run/serve": "^2.5.0",
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        isbot: "^4.0.0",
      },
      devDependencies: {
        "@remix-run/dev": "^2.5.0",
        vite: "^5.1.0",
        typescript: "^5.3.3",
      },
    }),
    "app/root.tsx": `import { Links, Meta, Outlet, Scripts } from "@remix-run/react";\nexport default function App() {\n  return (<html lang="en"><head><Meta /><Links /></head><body><Outlet /><Scripts /></body></html>);\n}\n`,
    "app/routes/_index.tsx": `export default function Index() {\n  return <main><h1>Remix AppForge app</h1></main>;\n}\n`,
    "vite.config.ts": `import { vitePlugin as remix } from "@remix-run/dev";\nimport { defineConfig } from "vite";\nexport default defineConfig({ plugins: [remix()] });\n`,
    "README.md": "# Remix App\n\n```bash\nnpm i && npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "vanilla-node": () => ({
    "package.json": pkg("vanilla-app", {
      dependencies: {},
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
    }),
    "index.html": `<!doctype html><html><body><h1 id="app">Vanilla AppForge</h1><script type="module" src="/src/main.js"></script></body></html>`,
    "src/main.js": `document.getElementById("app").textContent = "Vanilla AppForge app";\n`,
    "vite.config.js": `import { defineConfig } from "vite";\nexport default defineConfig({});\n`,
    "README.md": "# Vanilla App\n\n```bash\nnpm i && npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "react-python": () => ({
    ...viteReactShell("React + FastAPI"),
    "backend/main.py": `from fastapi import FastAPI\napp = FastAPI()\n@app.get("/health")\ndef health():\n    return {"ok": True}\n`,
    "backend/requirements.txt": "fastapi\nuvicorn\n",
  }),
  "react-django": () => ({
    ...viteReactShell("React + Django"),
    "backend/requirements.txt": "django\ndjangorestframework\n",
  }),
  "react-supabase": () =>
    viteReactShell("React Supabase App", {
      "@supabase/supabase-js": "^2.39.0",
    }),
  "astro-node": () => ({
    "package.json": pkg("astro-app", {
      scripts: {
        dev: "astro dev",
        build: "astro build",
        preview: "astro preview",
      },
      dependencies: { astro: "^4.0.0" },
    }),
    "src/pages/index.astro": `---\nconst title = "Astro AppForge app";\n---\n<html><body><h1>{title}</h1></body></html>\n`,
    "astro.config.mjs": `import { defineConfig } from "astro/config";\nexport default defineConfig({});\n`,
    "README.md": "# Astro App\n\n```bash\nnpm i && npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "phaser-html5": () => ({
    ...viteReactShell("Phaser Game", { phaser: "^3.70.0" }),
    "src/App.tsx": `import { useEffect, useRef } from "react";
import Phaser from "phaser";
export function App() {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!ref.current) return;
    const game = new Phaser.Game({
      type: Phaser.AUTO,
      width: 800,
      height: 450,
      parent: ref.current,
      backgroundColor: "#1a1a2e",
      scene: {
        create() {
          this.add.text(40, 40, "AppForge Phaser game", { color: "#fff", fontSize: "24px" });
        },
      },
    });
    return () => game.destroy(true);
  }, []);
  return <div ref={ref} />;
}
`,
  }),
  "three-js-3d": () => ({
    ...viteReactShell("Three.js Scene", { three: "^0.160.0" }),
    "src/App.tsx": `import { useEffect, useRef } from "react";
import * as THREE from "three";
export function App() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current!;
    const renderer = new THREE.WebGLRenderer({ canvas });
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(60, 16 / 9, 0.1, 100);
    camera.position.z = 3;
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshNormalMaterial());
    scene.add(mesh);
    let id = 0;
    const tick = () => {
      mesh.rotation.y += 0.01;
      renderer.setSize(800, 450);
      renderer.render(scene, camera);
      id = requestAnimationFrame(tick);
    };
    tick();
    return () => cancelAnimationFrame(id);
  }, []);
  return <canvas ref={ref} />;
}
`,
  }),
  "babylon-js-3d": () =>
    viteReactShell("Babylon Scene", { "@babylonjs/core": "^6.0.0" }),
  "unity-webgl": () => ({
    "index.html": `<!doctype html><html><body><h1>Unity WebGL shell</h1><p>Drop Unity WebGL build into /Build</p></body></html>`,
    "README.md":
      "# Unity WebGL\nExport from Unity and place files under Build/.\n",
    ".gitignore": GITIGNORE,
  }),
  "godot-html5": () => ({
    "index.html": `<!doctype html><html><body><h1>Godot HTML5 shell</h1></body></html>`,
    "README.md": "# Godot HTML5\nExport from Godot 4 and place files here.\n",
    ".gitignore": GITIGNORE,
  }),
  "react-native-game": () => viteReactShell("RN Game Loop"),
  "flutter-game": () => ({
    "pubspec.yaml": `name: appforge_game\ndescription: AppForge Flutter Flame game\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\n  flame: ^1.14.0\n`,
    "lib/main.dart": `import 'package:flutter/material.dart';\nvoid main() => runApp(const MaterialApp(home: Scaffold(body: Center(child: Text('AppForge Flame game')))));\n`,
    "README.md":
      "# Flutter Flame game\n\n```bash\nflutter pub get && flutter run\n```\n",
    ".gitignore": `.dart_tool\nbuild\n.flutter-plugins\n`,
  }),
  "ai-agent-python": () => pythonAgentShell("AI Agent Python"),
  "ai-agent-node": () => ({
    ...expressApiShell("AI Agent Node"),
    "src/agent.ts": `export async function runAgent(prompt: string) {
  const key = process.env.OPENAI_API_KEY || process.env.BUILT_IN_FORGE_API_KEY;
  if (!key) return { reply: "Set OPENAI_API_KEY", prompt };
  return { reply: "Agent scaffold received: " + prompt };
}
`,
  }),
  "openai-tool": () => expressApiShell("OpenAI Tool"),
  "langchain-tool": () => pythonAgentShell("LangChain Tool"),
  "crewai-agent": () => pythonAgentShell("CrewAI Agent"),
  "autogen-agent": () => pythonAgentShell("AutoGen Agent"),
  "electron-react": () => ({
    ...viteReactShell("Electron App"),
    "electron/main.cjs": `const { app, BrowserWindow } = require("electron");
app.whenReady().then(() => {
  const win = new BrowserWindow({ width: 1100, height: 720 });
  win.loadURL(process.env.VITE_DEV_SERVER_URL || "http://localhost:5173");
});
`,
    "package.json": pkg("electron-app", {
      scripts: {
        dev: "vite",
        build: "vite build",
        start: "electron .",
        electron: "electron .",
      },
      dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" },
      devDependencies: {
        electron: "^28.0.0",
        "@vitejs/plugin-react": "^4.2.1",
        vite: "^5.1.0",
        typescript: "^5.3.3",
      },
      main: "electron/main.cjs",
    }),
  }),
  "tauri-rust": () => ({
    ...viteReactShell("Tauri App"),
    "src-tauri/tauri.conf.json": JSON.stringify(
      {
        productName: "AppForge",
        version: "0.1.0",
        identifier: "com.appforge.app",
        build: {
          beforeDevCommand: "npm run dev",
          beforeBuildCommand: "npm run build",
          devUrl: "http://localhost:5173",
          frontendDist: "../dist",
        },
      },
      null,
      2,
    ),
    "src-tauri/Cargo.toml": `[package]\nname = "appforge"\nversion = "0.1.0"\nedition = "2021"\n[dependencies]\ntauri = { version = "2", features = [] }\n`,
  }),
  "react-native-expo": () => ({
    "package.json": pkg("expo-app", {
      scripts: {
        start: "expo start",
        android: "expo start --android",
        ios: "expo start --ios",
      },
      dependencies: {
        expo: "~51.0.0",
        react: "18.2.0",
        "react-native": "0.74.0",
      },
    }),
    "App.tsx": `import { Text, View } from "react-native";\nexport default function App() {\n  return <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}><Text>AppForge Expo</Text></View>;\n}\n`,
    "app.json": JSON.stringify(
      { expo: { name: "AppForge", slug: "appforge", version: "1.0.0" } },
      null,
      2,
    ),
    "babel.config.js": `module.exports = function (api) {\n  api.cache(true);\n  return { presets: ["babel-preset-expo"] };\n};\n`,
    "metro.config.js": `const { getDefaultConfig } = require("expo/metro-config");\nmodule.exports = getDefaultConfig(__dirname);\n`,
    "README.md": "# Expo App\n\n```bash\nnpm i && npx expo start\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "flutter-firebase": () => ({
    "pubspec.yaml": `name: appforge_flutter\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\n  firebase_core: ^2.24.0\n`,
    "lib/main.dart": `import 'package:flutter/material.dart';\nvoid main() => runApp(const MaterialApp(home: Scaffold(body: Center(child: Text('AppForge Flutter')))));\n`,
    "README.md": "# Flutter + Firebase\n",
    ".gitignore": `.dart_tool\nbuild\n`,
  }),
  "capacitor-ionic": () => viteReactShell("Ionic Capacitor App"),
  "chrome-extension": () => ({
    "manifest.json": JSON.stringify(
      {
        manifest_version: 3,
        name: "AppForge Extension",
        version: "0.1.0",
        action: { default_popup: "popup.html" },
        permissions: ["storage"],
      },
      null,
      2,
    ),
    "popup.html": `<!doctype html><html><body><h1>AppForge</h1><script src="popup.js"></script></body></html>`,
    "popup.js": `document.body.insertAdjacentHTML("beforeend", "<p>Extension ready</p>");\n`,
    "README.md": "# Chrome Extension MV3\nLoad unpacked from this folder.\n",
    ".gitignore": GITIGNORE,
  }),
  "vscode-extension": () => ({
    "package.json": JSON.stringify(
      {
        name: "appforge-vscode",
        displayName: "AppForge",
        version: "0.0.1",
        engines: { vscode: "^1.85.0" },
        categories: ["Other"],
        activationEvents: ["onCommand:appforge.hello"],
        main: "./extension.js",
        contributes: {
          commands: [{ command: "appforge.hello", title: "AppForge: Hello" }],
        },
      },
      null,
      2,
    ),
    "extension.js": `const vscode = require("vscode");
function activate(context) {
  context.subscriptions.push(
    vscode.commands.registerCommand("appforge.hello", () => {
      vscode.window.showInformationMessage("Hello from AppForge");
    }),
  );
}
module.exports = { activate, deactivate: () => {} };
`,
    "README.md": "# VS Code Extension\n",
    ".gitignore": GITIGNORE,
  }),
  "discord-bot": () => ({
    "package.json": pkg("discord-bot", {
      scripts: {
        dev: "tsx watch src/bot.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/bot.js",
        test: "vitest run",
      },
      dependencies: {
        "discord.js": "^14.14.1",
        dotenv: "^16.4.0",
      },
      devDependencies: {
        "@types/node": "^20.11.16",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
        vitest: "^1.2.2",
      },
    }),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "src/bot.ts": `import "dotenv/config";
import { Client, GatewayIntentBits, Events } from "discord.js";

const client = new Client({ intents: [GatewayIntentBits.Guilds] });
client.once(Events.ClientReady, (c) => console.log("Discord bot ready as", c.user.tag));
client.login(process.env.DISCORD_TOKEN);
`,
    "README.md":
      "# Discord Bot\n\n```bash\nnpm i && DISCORD_TOKEN=... npm run dev\n```\n\nDeploy with Fly/Railway as a long-running worker.\n",
    ".gitignore": GITIGNORE,
  }),
  "telegram-bot": () => ({
    "package.json": pkg("telegram-bot", {
      scripts: {
        dev: "tsx watch src/bot.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/bot.js",
      },
      dependencies: { telegraf: "^4.15.0", dotenv: "^16.4.0" },
      devDependencies: {
        "@types/node": "^20.11.16",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
      },
    }),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          skipLibCheck: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "src/bot.ts": `import "dotenv/config";
import { Telegraf } from "telegraf";

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN || "");
bot.start((ctx) => ctx.reply("AppForge Telegram bot online"));
bot.launch();
process.once("SIGINT", () => bot.stop("SIGINT"));
`,
    "README.md":
      "# Telegram Bot\n\n```bash\nnpm i && TELEGRAM_BOT_TOKEN=... npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "slack-bot": () => ({
    "package.json": pkg("slack-bot", {
      scripts: {
        dev: "tsx watch src/bot.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/bot.js",
      },
      dependencies: { "@slack/bolt": "^3.17.0", dotenv: "^16.4.0" },
      devDependencies: {
        "@types/node": "^20.11.16",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
      },
    }),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          skipLibCheck: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "src/bot.ts": `import "dotenv/config";
import { App } from "@slack/bolt";

const app = new App({
  token: process.env.SLACK_BOT_TOKEN,
  signingSecret: process.env.SLACK_SIGNING_SECRET,
});
app.message("hello", async ({ say }) => { await say("AppForge Slack bot online"); });
(async () => {
  await app.start(process.env.PORT || 3000);
  console.log("Slack bot running");
})();
`,
    "README.md":
      "# Slack Bot\n\n```bash\nnpm i && SLACK_BOT_TOKEN=... SLACK_SIGNING_SECRET=... npm run dev\n```\n",
    ".gitignore": GITIGNORE,
  }),
  "browser-automation": () => ({
    "package.json": pkg("browser-automation", {
      scripts: { start: "tsx src/run.ts", test: "vitest run" },
      dependencies: { playwright: "^1.41.0" },
      devDependencies: {
        tsx: "^4.7.0",
        typescript: "^5.3.3",
        vitest: "^1.2.2",
      },
    }),
    "src/run.ts": `import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto("https://example.com");
console.log(await page.title());
await browser.close();
`,
    "README.md": "# Browser automation\n",
    ".gitignore": GITIGNORE,
  }),
  "web-scraper": () => pythonAgentShell("Web Scraper"),
  "data-visualization": () => viteReactShell("Data Viz", { d3: "^7.8.5" }),
  "api-service": () => expressApiShell("API Service"),
  "serverless-aws": () => ({
    "package.json": pkg("aws-lambda-api", {
      scripts: {
        build:
          "esbuild src/handler.ts --bundle --platform=node --outfile=dist/handler.js",
      },
      dependencies: {},
      devDependencies: {
        esbuild: "^0.20.0",
        typescript: "^5.3.3",
        "@types/aws-lambda": "^8.10.0",
      },
    }),
    "src/handler.ts": `export const handler = async () => ({ statusCode: 200, body: JSON.stringify({ ok: true }) });\n`,
    "README.md": "# AWS Lambda\n",
    ".gitignore": GITIGNORE,
  }),
  "serverless-vercel": () => ({
    "package.json": pkg("vercel-functions", {
      scripts: { dev: "vercel dev", deploy: "vercel deploy --prod" },
    }),
    "api/hello.ts": `export default function handler(_req: any, res: any) {
  res.status(200).json({ ok: true });
}
`,
    "vercel.json": JSON.stringify({ version: 2 }, null, 2),
    "README.md": "# Vercel Serverless\n",
    ".gitignore": GITIGNORE,
  }),
};

export function getStackScaffold(techStack: string): Files {
  const factory = SCAFFOLDS[techStack];
  if (factory) return factory();
  return viteReactShell(`${techStack} App`);
}

export function mergeScaffoldWithGenerated(
  scaffold: Files,
  generated: Files,
): Files {
  const out: Files = { ...scaffold, ...generated };

  if (scaffold["package.json"] && generated["package.json"]) {
    try {
      const base = JSON.parse(scaffold["package.json"]) as Record<string, any>;
      const over = JSON.parse(generated["package.json"]) as Record<string, any>;
      out["package.json"] = JSON.stringify(
        {
          ...base,
          ...over,
          scripts: { ...(base.scripts || {}), ...(over.scripts || {}) },
          dependencies: {
            ...(base.dependencies || {}),
            ...(over.dependencies || {}),
          },
          devDependencies: {
            ...(base.devDependencies || {}),
            ...(over.devDependencies || {}),
          },
        },
        null,
        2,
      );
    } catch {
      // keep generated package.json
    }
  }
  return out;
}

export default { getStackScaffold, mergeScaffoldWithGenerated };
