export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.COOKIE_SECRET ?? process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? process.env.SUPABASE_DB_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerEmail: process.env.OWNER_EMAIL ?? "anselm.perkins@gmail.com",
  ownerPhone: process.env.OWNER_PHONE ?? "+64224553315",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  supabaseUrl: process.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "",
  supabaseServiceKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripeStarterPriceId: process.env.STRIPE_STARTER_PRICE_ID ?? "",
  stripeBuilderPriceId: process.env.STRIPE_BUILDER_PRICE_ID ?? "",
  stripeStudioPriceId: process.env.STRIPE_STUDIO_PRICE_ID ?? "",
  stripeEnterprisePriceId: process.env.STRIPE_ENTERPRISE_PRICE_ID ?? "",
  stripeCustomPriceId: process.env.STRIPE_CUSTOM_PRICE_ID ?? "",
  stripeStarterPaymentLink: process.env.STRIPE_STARTER_PAYMENT_LINK ?? "",
  stripeBuilderPaymentLink: process.env.STRIPE_BUILDER_PAYMENT_LINK ?? "",
  stripeStudioPaymentLink: process.env.STRIPE_STUDIO_PAYMENT_LINK ?? "",
  sentryDsn: process.env.SENTRY_DSN ?? "",
  sentryTracesSampleRate: parseFloat(
    process.env.SENTRY_TRACES_SAMPLE_RATE ?? "0.1",
  ),
  corsOrigin: process.env.CORS_ORIGIN ?? "",
  requestTimeoutMs: parseInt(process.env.REQUEST_TIMEOUT_MS ?? "30000", 10),
  vercelToken: process.env.VERCEL_TOKEN ?? "",
  vercelTeamId: process.env.VERCEL_TEAM_ID ?? "",
  redisUrl: process.env.REDIS_URL ?? "",
  logtailSourceToken: process.env.LOGTAIL_SOURCE_TOKEN ?? "",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioPhoneNumber: process.env.TWILIO_PHONE_NUMBER ?? "",
  hCaptchaSecret: process.env.HCAPTCHA_SECRET ?? "",
  vantaWorkspaceId: process.env.VANTA_WORKSPACE_ID ?? "",
  vantaApiToken: process.env.VANTA_API_TOKEN ?? "",
  tavilyApiKey: process.env.TAVILY_API_KEY ?? "",
  serpApiKey: process.env.SERPAPI_API_KEY ?? process.env.SERP_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
};
