import { useState } from 'react';

type Props = { children: React.ReactNode };
export default function LandingEnhancements({ children }: Props) {
  const [dark, setDark] = useState(false), [language, setLanguage] = useState('English'), [account, setAccount] = useState<'signin' | 'signup' | null>(null);
  const bg = dark ? '#06101e' : '#f8fbff', fg = dark ? '#e7eefb' : '#10243e';
  return <div style={{ background: bg, color: fg, minHeight: '100vh' }}>
    <div style={{ position: 'fixed', right: 18, top: 16, zIndex: 30, display: 'flex', gap: 8, alignItems: 'center', fontFamily: 'Inter,system-ui,sans-serif' }}>
      <select value={language} onChange={e => setLanguage(e.target.value)} aria-label="Language" style={{ padding: 9, borderRadius: 8, border: '1px solid #cbd5e1' }}><option>English</option><option>Te Reo Māori</option><option>Español</option><option>Français</option></select>
      <button onClick={() => setDark(!dark)} style={{ padding: '9px 11px', borderRadius: 8, border: '1px solid #cbd5e1', background: '#fff' }}>{dark ? '☀ Day' : '◐ Night'}</button>
      <button onClick={() => setAccount('signin')} style={{ padding: '9px 12px', borderRadius: 8, border: '1px solid #cbd5e1', background: '#fff' }}>Sign in</button>
      <button onClick={() => setAccount('signup')} style={{ padding: '9px 12px', borderRadius: 8, border: 0, background: '#2563eb', color: '#fff', fontWeight: 800 }}>Create account</button>
    </div>
    <div style={dark ? { filter: 'brightness(.86) saturate(.9)' } : undefined}>{children}</div>
    <section id="pricing" style={{ padding: '84px 24px', background: dark ? '#09192d' : '#fff', fontFamily: 'Inter,system-ui,sans-serif' }}><div style={{ maxWidth: 1120, margin: '0 auto' }}><p style={{ color: '#2563eb', fontWeight: 800, fontSize: 12, letterSpacing: '.1em' }}>TRANSPARENT PRICING</p><h2 style={{ fontSize: 42, margin: '10px 0', color: fg }}>Choose the build capacity you need.</h2><p style={{ color: dark ? '#cbd5e1' : '#5d6c80' }}>No hidden deployment claims. Each plan shows the included build capacity before checkout.</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 18, marginTop: 30 }}>{[['Free','Explore the workflow','1 saved project','Plan and workspace access'],['Starter','For focused prototypes','5 build credits / month','Saved artifacts and GitHub export'],['Builder','For active product work','25 build credits / month','Priority generation and build history'],['Studio','For teams','100 build credits / month','Shared projects and priority support']].map(([name,tag,a,b]) => <article key={name} style={{ border: '1px solid #dbe4ef', borderRadius: 16, padding: 22, background: dark ? '#10243e' : '#fff' }}><h3 style={{ fontSize: 22, margin: 0, color: dark ? '#fff' : '#10243e' }}>{name}</h3><p style={{ color: '#2563eb', fontWeight: 700 }}>{tag}</p><p style={{ color: dark ? '#d7e3f6' : '#5d6c80' }}>✓ {a}<br />✓ {b}</p><button onClick={() => setAccount(name === 'Free' ? 'signup' : 'signup')} style={{ padding: '10px 14px', borderRadius: 8, border: 0, background: '#2563eb', color: '#fff', fontWeight: 800 }}>{name === 'Free' ? 'Start free' : 'Choose plan'}</button></article>)}</div></div></section>
    {account && <div role="dialog" aria-modal="true" style={{ position: 'fixed', inset: 0, zIndex: 50, background: 'rgba(2,6,23,.68)', display: 'grid', placeItems: 'center', padding: 20 }}><form onSubmit={e => { e.preventDefault(); }} style={{ width: 'min(420px,100%)', background: '#fff', borderRadius: 18, padding: 28, color: '#10243e' }}><button type="button" onClick={() => setAccount(null)} style={{ float: 'right', border: 0, background: 'transparent', fontSize: 20 }}>×</button><h2>{account === 'signin' ? 'Sign in to AppForge' : 'Create your AppForge account'}</h2><p style={{ color: '#5d6c80' }}>{account === 'signin' ? 'Continue to your projects and build history.' : 'Start with a project, then build deliberately.'}</p><input type="email" placeholder="Email" required style={{ width: '100%', boxSizing: 'border-box', padding: 12, margin: '8px 0', borderRadius: 8, border: '1px solid #cbd5e1' }} /><input type="password" placeholder="Password" required style={{ width: '100%', boxSizing: 'border-box', padding: 12, margin: '8px 0', borderRadius: 8, border: '1px solid #cbd5e1' }} /><button type="submit" style={{ width: '100%', padding: 12, marginTop: 10, border: 0, borderRadius: 8, background: '#2563eb', color: '#fff', fontWeight: 800 }}>{account === 'signin' ? 'Sign in' : 'Create account'}</button></form></div>}
  </div>;
}
