import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { router, ownerOnlyProcedure, protectedProcedure } from "../_core/trpc.js";
import { db } from "../db.js";
import { applyGodCodeGrant } from "../dbGrants.js";
import * as schema from "../db/schema.js";
import { eq, desc, and, gte, count, sql, isNull } from "drizzle-orm";
import { ENV } from "../_core/env.js";
import { logger } from "../_core/logger.js";
import { encryptGodCode, hashGodCode, mintGodCode } from "../lib/serverSecrets.js";
import { createHash } from "crypto";
