import crypto from 'node:crypto';

export const config = { api: { bodyParser: false } };
const planForPrice = {
  [process.env.STRIPE_PRICE_STARTER]: ['starter', 2],
  [process.env.STRIPE_PRICE_BUILDER]: ['builder', 8],
  [process.env.STRIPE_PRICE_STUDIO]: ['studio', 30],
};
const rawBody = req => new Promise((resolve, reject) => { const chunks = []; req.on('data', chunk => chunks.push(chunk)); req.on('end', () => resolve(Buffer.concat(chunks))); req.on('error', reject); });
const supabaseHeaders = { apikey: process.env.SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`, 'Content-Type': 'application/json' };
async function stripe(path) { const response = await fetch(`https://api.stripe.com/v1${path}`, { headers: { Authorization: `Bearer ${process.env.STRIPE_SECRET_KEY}` } }); if (!response.ok) throw new Error('Stripe lookup failed.'); return response.json(); }
async function entitlementBySubscription(subscriptionId) { const response = await fetch(`${process.env.SUPABASE_URL}/rest/v1/appforge_entitlements?stripe_subscription_id=eq.${encodeURIComponent(subscriptionId)}&select=user_id`, { headers: supabaseHeaders }); const rows = await response.json(); return rows?.[0] || null; }
async function markEvent(event) { const response = await fetch(`${process.env.SUPABASE_URL}/rest/v1/stripe_webhook_events`, { method: 'POST', headers: { ...supabaseHeaders, Prefer: 'resolution=ignore-duplicates,return=representation' }, body: JSON.stringify({ stripe_event_id: event.id, event_type: event.type }) }); const rows = await response.json().catch(() => []); return response.ok && Array.isArray(rows) && rows.length === 1; }
async function syncSubscription(subscription, userId) { const [plan, credits] = planForPrice[subscription.items?.data?.[0]?.price?.id] || ['free', 0]; const active = subscription.status === 'active'; const response = await fetch(`${process.env.SUPABASE_URL}/rest/v1/appforge_entitlements?on_conflict=user_id`, { method: 'POST', headers: { ...supabaseHeaders, Prefer: 'resolution=merge-duplicates' }, body: JSON.stringify({ user_id: userId, stripe_customer_id: String(subscription.customer), stripe_subscription_id: subscription.id, stripe_price_id: subscription.items?.data?.[0]?.price?.id || null, plan, subscription_status: subscription.status, monthly_build_credits: active ? credits : 0, build_credits_remaining: active ? credits : 0, current_period_end: subscription.current_period_end ? new Date(subscription.current_period_end * 1000).toISOString() : null }) }); if (!response.ok) throw new Error('Unable to sync AppForge entitlement.'); }
export default async function handler(req, res) { if (req.method !== 'POST') return res.status(405).end(); if (!process.env.STRIPE_WEBHOOK_SECRET || !process.env.STRIPE_SECRET_KEY || !process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return res.status(503).send('Webhook is not configured.'); const body = await rawBody(req); const signature = req.headers['stripe-signature'] || ''; const values = Object.fromEntries(signature.split(',').map(part => part.split('='))); const expected = crypto.createHmac('sha256', process.env.STRIPE_WEBHOOK_SECRET).update(`${values.t}.${body}`).digest('hex'); const supplied = values.v1 || ''; if (!values.t || !supplied || supplied.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(supplied))) return res.status(400).send('Invalid signature.'); const event = JSON.parse(body); if (!(await markEvent(event))) return res.status(200).json({ received: true, duplicate: true }); try { if (event.type === 'checkout.session.completed') { const session = event.data.object; if (!session.client_reference_id || !session.subscription) throw new Error('Checkout is missing AppForge user context.'); await syncSubscription(await stripe(`/subscriptions/${session.subscription}`), session.client_reference_id); } if (event.type === 'customer.subscription.updated' || event.type === 'customer.subscription.deleted') { const subscription = event.data.object; const entitlement = await entitlementBySubscription(subscription.id); if (entitlement?.user_id) await syncSubscription(subscription, entitlement.user_id); } if (event.type === 'invoice.paid' || event.type === 'invoice.payment_failed') { const subscriptionId = event.data.object.subscription; if (subscriptionId) { const entitlement = await entitlementBySubscription(subscriptionId); if (entitlement?.user_id) await syncSubscription(await stripe(`/subscriptions/${subscriptionId}`), entitlement.user_id); } } return res.status(200).json({ received: true }); } catch (error) { return res.status(500).json({ error: error instanceof Error ? error.message : 'Webhook processing failed.' }); } }
